name: Daily Instagram -> Facebook

permissions:
  contents: write

on:
  schedule:
    - cron: '0 8 * * *'   # daily 08:00 UTC
  workflow_dispatch:

jobs:
  post_instagram:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          INSTAGRAM_PROFILE: ${{ secrets.INSTAGRAM_PROFILE }}   # username of the public IG page
          FACEBOOK_PAGE_ID: ${{ secrets.FACEBOOK_PAGE_ID }}
          FACEBOOK_PAGE_ACCESS_TOKEN: ${{ secrets.FACEBOOK_PAGE_ACCESS_TOKEN }}
          MAX_RESULTS: "5"
        run: python main.py

      - name: Commit posted_cache.json
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add posted_cache.json
          git commit -m "Update posted_cache.json [skip ci]" || echo "No changes to commit"
          git push
