name: Daily Instagram -> Facebook

permissions:
  contents: write  # allows updating posted_cache.json

on:
  schedule:
    - cron: '0 8 * * *'   # runs daily at 08:00 UTC
  workflow_dispatch:

jobs:
  post_instagram:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Instagram -> Facebook script
        env:
          INSTAGRAM_PROFILE: ${{ secrets.INSTAGRAM_PROFILE }}
          FACEBOOK_PAGE_ID: ${{ secrets.FACEBOOK_PAGE_ID }}
          FACEBOOK_PAGE_ACCESS_TOKEN: ${{ secrets.FACEBOOK_PAGE_ACCESS_TOKEN }}
          MAX_RESULTS: "5"
          REQUEST_TIMEOUT: "60"

          # Preferred: session-based auth (create locally and store base64 in secret)
          INSTALOADER_USERNAME: ${{ secrets.INSTALOADER_USERNAME }}
          INSTALOADER_SESSION_B64: ${{ secrets.INSTALOADER_SESSION_B64 }}

          # Optional fallback (not recommended if you have session file)
          # INSTALOADER_PASSWORD: ${{ secrets.INSTALOADER_PASSWORD }}
        run: python main.py

      - name: Commit updated posted_cache.json
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add posted_cache.json
          git commit -m "Update posted_cache.json [skip ci]" || echo "No changes to commit"
          git push
