name: Daily YouTube to Facebook

on:
  schedule:
    # Runs every day at 08:00 UTC
    - cron: '0 8 * * *'
  workflow_dispatch: # Allows manual run

jobs:
  post_videos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests yt-dlp

      - name: Run main.py
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          FACEBOOK_PAGE_ID: ${{ secrets.FACEBOOK_PAGE_ID }}
          FACEBOOK_PAGE_ACCESS_TOKEN: ${{ secrets.FACEBOOK_PAGE_ACCESS_TOKEN }}
          YOUTUBE_COOKIES: ${{ secrets.YOUTUBE_COOKIES_B64 }}
        run: python main.py

      - name: Commit updated posted_cache.json
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add posted_cache.json
          git commit -m "Update posted_cache.json [skip ci]" || echo "No changes to commit"
          git push
